/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicotres;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;


/**
 *
 * @author Rodrigo
 */
public class Ejercicio2Prin extends javax.swing.JPanel {

    /**
     * Creates new form Ejercicio2Prin
     */
    public Ejercicio2Prin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2Prin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroCirc = new javax.swing.JTextField();
        espesor = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel2Prin.setPreferredSize(new java.awt.Dimension(346, 346));

        javax.swing.GroupLayout panel2PrinLayout = new javax.swing.GroupLayout(panel2Prin);
        panel2Prin.setLayout(panel2PrinLayout);
        panel2PrinLayout.setHorizontalGroup(
            panel2PrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        panel2PrinLayout.setVerticalGroup(
            panel2PrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jLabel1.setText("Ingrese Número de circunferencias");

        jLabel2.setText("Ingrese espesor de circunferencia");

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroCirc)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(espesor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(panel2Prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panel2Prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(numeroCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(espesor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
            Random rand;
            int  N = Integer.parseInt(numeroCirc.getText());
            int E = Integer.parseInt(espesor.getText());
            if (N > 20 || N < 3 || E > 20 || E < 3) {
                throw new MisException("1");
            }
            rand= new Random();
            rand.setSeed(new Date().getTime());
           int auxiliar1=rand.nextInt((int)(0.2*this.panel2Prin.getWidth()))+(int)(0.5*((double)E))+E;
            
            if((this.panel2Prin.getHeight()-auxiliar1-E)<(N*E*2)){
            
                throw new MisException("3");
            }
            
            dibujar(N,E,auxiliar1);
       }
       catch (MisException ex) {
            numeroCirc.setText(null);
            espesor.setText(null);
        }
       catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese valores enteros", "Error", JOptionPane.WARNING_MESSAGE);
            numeroCirc.setText(null);
            espesor.setText(null);
        }
         
    }//GEN-LAST:event_jButton5ActionPerformed

    
    void dibujar(int N,int E, int auxiliar1) {

        this.panel2Prin.removeAll();
        Ejercicio1Aux aux;
        aux = new Ejercicio1Aux(N, E, 2,auxiliar1);
        aux.setSize(this.panel2Prin.getWidth(), this.panel2Prin.getHeight());
        aux.setLocation(0, 0);
        aux.setBackground(Color.white);

        this.panel2Prin.add(aux, BorderLayout.CENTER);
        // this.revalidate(); //busca una validacion entre los metodos para verificar q todo sea correcto
        this.repaint(); // este actualiza lo q seria el dibujo
        //updateUI(); //este metodo es como q actualiza toda la interfaz
         aux.setBackground(Color.white);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField espesor;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numeroCirc;
    private javax.swing.JPanel panel2Prin;
    // End of variables declaration//GEN-END:variables

}
